steps:
  debug:
    image: alpine
    commands:
      - echo "✅ Pipeline backend déclenché sur ${CI_COMMIT_BRANCH}"
      - "echo Event déclencheur : ${CI_PIPELINE_EVENT}"
    when:
      event: [push, manual, pull_request]

  build:
    image: python:3.11
    commands:
      - echo "📦 Build backend"
      - pip install -r requirements.txt
      - echo "✅ Tests backend à venir"
    when:
      branch: [staging, prod]
      event: [push, manual]

  prepare-secrets:
    image: alpine
    commands:
      - rm -rf /tmp/gcp-credentials.json
      - echo "$GOOGLE_CREDENTIALS_JSON" > /tmp/gcp-credentials.json
    environment:
      GOOGLE_CREDENTIALS_JSON:
        from_secret: GOOGLE_CREDENTIALS_JSON
    when:
      branch: [staging, prod]
      event: [push, manual]



  deploy-staging:
    image: docker/compose:1.29.2
    privileged: true
    depends_on: [build, prepare-secrets]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gcp-credentials.json:/tmp/gcp-credentials.json
    environment:
      DJANGO_SECRET_KEY:
        from_secret: DJANGO_SECRET_KEY
      DB_HOST:
        from_secret: DB_HOST
      DB_PORT:
        from_secret: DB_PORT
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_NAME:
        from_secret: DB_NAME
      SIGNING_SECRET:
        from_secret: SIGNING_SECRET
      GS_BUCKET_NAME:
        from_secret: GS_BUCKET_NAME
      GS_PROJECT_ID:
        from_secret: GS_PROJECT_ID
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-credentials.json
    commands:
      - docker-compose -f docker/staging/docker-compose.yml -p qip_api_staging down --remove-orphans || true
      - docker rm -f qip_api_staging || true
      - docker-compose -f docker/staging/docker-compose.yml -p qip_api_staging up -d --build --remove-orphans
      - docker-compose -f docker/staging/docker-compose.yml -p qip_api_staging run --rm pytest
    when:
      branch: [staging]
      event: [push, manual]

  deploy-prod:
    image: docker/compose:1.29.2
    privileged: true
    depends_on: [build, prepare-secrets]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gcp-credentials.json:/tmp/gcp-credentials.json
    environment:
      DJANGO_SECRET_KEY:
        from_secret: DJANGO_SECRET_KEY
      DB_HOST:
        from_secret: DB_HOST
      DB_PORT:
        from_secret: DB_PORT
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_NAME:
        from_secret: DB_NAME
      SIGNING_SECRET:
        from_secret: SIGNING_SECRET
      GS_BUCKET_NAME:
        from_secret: GS_BUCKET_NAME
      GS_PROJECT_ID:
        from_secret: GS_PROJECT_ID
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-credentials.json
    commands:
      - docker-compose -f docker/prod/docker-compose.yml -p qip_api_prod down --remove-orphans || true
      - docker rm -f qip_api_prod || true
      - docker-compose -f docker/prod/docker-compose.yml -p qip_api_prod up -d --build --remove-orphans
    when:
      branch: [prod]
      event: [push, manual]
